#!/usr/bin/env python

########################################################################################################################
# DETAILS ##############################################################################################################
########################################################################################################################
# @author: 	Benjamin S. Meyers
# @email:	lion.logic.org@gmail.com
########################################################################################################################
# COPYRIGHT INFORMATION ################################################################################################
########################################################################################################################
__copyright__ = """
Copyright (C) 2015, Benjamin S. Meyers <bsm9339@rit.edu>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License version 2 as
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
MA 02110-1301 USA
"""

########################################################################################################################
# IMPORTS ##############################################################################################################
########################################################################################################################
import sys, os
from lib.pyostat_functions import iostat_command, verbose_seen, display_output
from lib.pyostat_device import out_files, set_path


########################################################################################################################
# MAIN #################################################################################################################
########################################################################################################################
def main():
	last_arg = sys.argv[-1]
	if os.path.isdir(last_arg) or last_arg == '':
		if last_arg != '' and last_arg[-1] != '/':
			last_arg += '/'
		set_path(last_arg)

	prog = os.path.basename(sys.argv[0])
	try:
		iostat_command(prog)
	except KeyboardInterrupt:
		print('Caught ^C... exiting...')
		if verbose_seen:
			out_files['127.0.0.1'].write('###### END VERBOSE OUTPUT ######\n')
			sys.exit(1)
		elif display_output:
			out_files['127.0.0.1'].write('###### END STANDARD OUTPUT ######\n')
			sys.exit(1)

	if verbose_seen:
		out_files['127.0.0.1'].write('###### END VERBOSE OUTPUT ######\n')
		sys.exit(0)
	elif display_output:
		out_files['127.0.0.1'].write('###### END STANDARD OUTPUT ######\n')
		sys.exit(0)


if __name__ == "__main__":
	main()
