#!/usr/bin/env python

########################################################################################################################
# DETAILS ##############################################################################################################
########################################################################################################################
# @author: 	Benjamin S. Meyers
# @email:	lion.logic.org@gmail.com
########################################################################################################################
# COPYRIGHT INFORMATION ################################################################################################
########################################################################################################################
__copyright__ = """
Copyright (C) 2015, Benjamin S. Meyers <bsm9339@rit.edu>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License version 2 as
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
MA 02110-1301 USA
"""

########################################################################################################################
# IMPORTS ##############################################################################################################
########################################################################################################################
import sys
import os
from lib.pyostat_functions import iostat_command, verbose_seen
from lib.pyostat_device import out_files


########################################################################################################################
# MAIN #################################################################################################################
########################################################################################################################
def main():
	prog = os.path.basename(sys.argv[0])
	try:
		iostat_command()
	except KeyboardInterrupt:
		print('Caught ^C... exiting...')
		out_files['127.0.0.1'].write('###### END VERBOSE OUTPUT ######\n')
		sys.exit(1)

	if verbose_seen:
		out_files['127.0.0.1'].write('###### END VERBOSE OUTPUT ######\n')
	sys.exit(0)


if __name__ == "__main__":
	main()
